version: "3.1"

services:
  app:
    image: "381353240263.dkr.ecr.us-east-1.amazonaws.com/app:1.0.103"
    container_name: app
    hostname: app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - PORT=5000
      - FLASK_DEBUG=1 
      - TEMPLATES_AUTO_RELOAD=1
      - DB_URI=mysql+pymysql://root:secret@mysql:3306/app-database #
    depends_on:
      - mysql
    restart: always
    networks: 
     - portfolio

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app-database
    volumes:
      - ./sql/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
      #- ./sql/:/etc/mysql/conf.d/
      #- ./database/:/var/lib/mysql/
    restart: always
    networks: 
     - portfolio


  nginx:
    image: "381353240263.dkr.ecr.us-east-1.amazonaws.com/nginx-app:1.0.103"
    container_name: nginx
    hostname: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     #- ./static/:/usr/share/nginx/html/static/
    ports:
      - 5005:80
    networks: 
     - portfolio

    #extra_hosts:
    # - host.docker.internal:host-gateway


networks:
  portfolio:
    external: true
      