apiVersion: apps/v1
kind: Deployment
metadata:
  name: friday-app
  labels:
    app: friday-app
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels:
      app: friday-app
  template:
    metadata:
      labels:
        app: friday-app
    spec:
      containers:
        - name: friday
          image: 381353240263.dkr.ecr.us-east-1.amazonaws.com/app:1.0.103 #{{ .Values.image_app }}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: FLASK_APP
              value: "app"
            - name: PORT
              value: "5000"
            - name: FLASK_DEBUG
              value: "1" 
            - name: TEMPLATES_AUTO_RELOAD
              value: "1"
            - name: DB_URI
              value: "mysql+pymysql://root:secret@mysql:3306/app-database" # {{ .Values.db_url }}

            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: MYSQL_DATABASE
              value: app-database
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      #imagePullSecrets:
      #  - name: ecr-registry-helper-secrets
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: friday-app
  type: NodePort