apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: friday-app
data:  
  nginx.conf: |
    events {} 
    http {
        include mime.types;
      server {
        listen 80 default_server;
        location /static/ {     #~ \.(jpg|png|js|xml|css) {
          root   /usr/share/nginx/html/static;
          add_header FROM_NGINX 'yes';
        }
  
        location / {
          proxy_pass         http://app-service:5000;
          proxy_redirect     off;
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
          add_header FROM_NGINX 'yes';
    
        }
      }
    }
    
    
    
